### PR TITLE
Link Myself

### PR DESCRIPTION
**Pull request by Elijah1111**
Credit where Credit is do

### CODE REVIEW

**Comment by Elijah1111** [comment]
It would be nice

**Comment by jacobwhall** [comment]
I indeed want to give credit where it is due! I see that you just licensed PiRadio under GPL-2.0, and I will do the same to this repository to ensure compatibility. Thanks :relaxed:

**Comment by jacobwhall** [comment]
Hey @Elijah1111 I've updated the license in 38b8a19 and README.md in 661f1be. I apologize for not seeking your permission for this project in the first place, and please let me know if there's anything else I can do to properly credit your work.

**Comment by Elijah1111** [comment]
Thanks! Its not that big of a deal.
Cheers

**Pull request merged**
